### ISSUE TITLE
Implement class expectations

### ISSUE THREAD

**Issue by kinto-b** [socialresearchcentre/testdat#33]
Something like this:

```r
expect_class(vars(am, vs), "double", data = mtcars)
#> Error: `am`, `vs` not of class `double`
#> Filter: None 
```

**Comment by kinto-b** [comment]
@gorcha returning to this, I'm thinking a better approach might be to implement a generic expectation operating column-wise:

```r
expect_each(everything(), func = is.numeric, func_desc = "numeric check", data = iris)
#> Error: `Species` fails numeric check
```

Thoughts?

**Comment by gorcha** [comment]
Hey @kinto-b,

Happy new year! 🎉

Would we be better off changing the message formatting for the `expect_all()` output so it references the variables that fail rather than creating a new function?
It would probably mean splitting out `expect_all()` and `expect_any()`, since `expect_any()` can only fail for all variables together, but that's probably not such a bad idea anyway.

**Comment by kinto-b** [comment]
@gorcha Happy new year! :) 

Yeah, maybe that would be preferable come to think of it. So we'd have:

```r
expect_all(
    vars = c(vs, am, gear, carb),
    func = function(x) x %in% 0:1,
    data = mtcars
)
#> Error: `mtcars` has 32 records failing `function(x) x %in% 0:1` on variable `gear, carb`.
#> Filter: None
#> Arguments: ``
```
 
(As a side note, I think it'd be nice if the variables came up as ``` `gear`, `carb` ``` rather than ``` `gear, carb` ```)

**Comment by gorcha** [comment]
Yup that looks about right, and agree on the variable formatting. The current formatting is because it's pulling in the call, so it doesn't actually evaluate the column names for the message (e.g. it would say `` `matches("blah")` `` rather than `` `blah1, blah2, blah3` ``. This will be different if this change is made, since we'll be listing the actual variables that failed rather than just the call info.

On that note, it's probably worth leaving the call info in there as well... Maybe something like this:
```r
expect_all(
    vars = c(vs, am, gear, carb),
    func = function(x) x %in% 0:1,
    data = mtcars
)
#> Error: `mtcars` has 32 records failing `function(x) x %in% 0:1` on variables `gear` and/or `carb`.
#> Vars: `c(vs, am, gear, carb)`
#> Filter: None
#> Arguments: ``
```

**Comment by kinto-b** [comment]
Yeah, good call. I might have a look at implementing this stuff. I'll put through a PR this week

**Comment by kinto-b** [comment]
@gorcha I've done the central bit of this issue, which was very simple. But it leaves a couple of loose ends:
1. Now that `expect_all` and `expect_any` have been split out, `expect_allany` is redundant. I wonder if we should consider moving toward deprecation. 
2. Other expectations (including `expect_any`) have the slightly unsightly ``` ... on variable `var1, var2` ```. It's a bit more of a project to clean this up. I'm reluctant to go down that path

Thoughts?

**Comment by gorcha** [comment]
Hey @kinto-b, I think totally fine to start deprecation of `expect_allany()`, it's only really there as a shared back end.

I also think that the current presentation of the var list is fine for the other expectations. `expect_all()` is a bit different because we can separate the failing vars from the full list, but most other expectations just fail as a whole and I think it's more useful to show the call rather than the specific variables that it resolves to.
Using the earlier example, showing the user `matches("blah")` rather than evaluating and showing `` `blah1`, `blah2`, `blah3` `` more clearly reflects the intent of the test.
