### ISSUE TITLE
Cannot test grouped data

### ISSUE THREAD

**Issue by kinto-b** [socialresearchcentre/testdat#68]
``` r
library(testdat)
library(dplyr)

mtcars %>% group_by(am) %>% expect_values(vs, 0:1, data = .)
#> Adding missing grouping variables: `am`
#> Error: Problem with `mutate()` input `..1`.
#> i `..1 = across(everything(), ~ifelse(flt$.cond, ., NA))`.
#> i `..1` must be size 19 or 1, not 32.
#> i The error occurred in group 1: am = 0.
```

<sup>Created on 2022-05-20 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by TiO2** [comment]
To apply function to dplyr grouped data, the documentation has it https://dplyr.tidyverse.org/reference/group_map.html 

Following seem working ok: 

mtcars %>%
  group_by(am)%>%
  group_map( ~ test_that("range between 0 and 1", {
    expect_values(vs, 0:1, data = .x)
  })  )
# both passed

mtcars %>%
  group_by(am)%>%
  group_map( ~ test_that("range between 0 and 1", {
    expect_values(vs, 0:0.5, data = .x)
  })  )
# Error in reporter$stop_if_needed() : Test failed

**Comment by kinto-b** [comment]
Thanks @TiO2. I think it's probably still worth refactoring to natively support grouped data. It's just a quirk of the implementation on the back-end that's preventing it from working

**Comment by gorcha** [comment]
Hey @kinto-b,

I'm leaning towards removing/ignoring groups if a grouped tibble is used (so they don't throw an error), but I can't really see a need for any further support.

The way I see it our focus is on testing data sets as a whole. If tests need to be run separately on each group then the grouping can be done outside of the test functions like in the example from @TiO2 above.

Happy to be convinced otherwise though!

**Comment by kinto-b** [comment]
@gorcha Oh no I agree. I really just meant fixing the bug that's preventing grouped data from being passed through. I can't really think of a good use-case for group-wise testing

**Comment by gorcha** [comment]
OK cool, easy! 🙂
